comment:
  require_changes: true

component_management:
  individual_components:
    - component_id: antithrow
      name: antithrow
      paths:
        - packages/antithrow
    - component_id: eslint-plugin
      name: "@antithrow/eslint-plugin"
      paths:
        - packages/eslint-plugin
    - component_id: node
      name: "@antithrow/node"
      paths:
        - packages/node
    - component_id: standard-schema
      name: "@antithrow/standard-schema"
      paths:
        - packages/standard-schema
    - component_id: std
      name: "@antithrow/std"
      paths:
        - packages/std
